# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v -o build/announcement-discord-api ./src

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: announcement-discord-api
          path: build/announcement-discord-api

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Test release
          release_name: Release!
          body: "Some Release"
          draft: false
          prerelease: false

    # - name: Test
    #   run: go test -v ./...
